### ISSUE TITLE
Parser não detecta anomalias de seção em log

### ISSUE THREAD

**Issue by vjoao** [danarrib/TSEParser#7]
O relatório de defeitos de carga é interessante. Fui verificar o defeito de votação antes da abertura da urna, mais especificamente a zona 121, seção 151 (Porto Seguro - BA) e notei que os arquivos de log dessa seção - baixados do site do TSE - incluem a seção 151 e a seção 194, como se um erro humano ao digitar a seção na urna de contingência produzisse logs que o seu parser não considera.

Talvez seja interessante extrair as linhas de cada arquivo de log para um arquivo ordenado por data e fazer parsing como um todo, analisando inclusive se a seção mudou em um mesmo conjunto de logs.

**Comment by danarrib** [comment]
Boa tarde Victor. 

Obrigado pelo interesse em olhar esses dados. Fico feliz que alguém também está interessado nisso.

Eu vou alterar o programa que lê os logs para que ele adicione, a cada voto computado, a informação da seção eleitoral a qual pertence aquele log, assim na hora de gerar o relatório eu posso excluir as zonas eleitorais que não são iguais a do boletim.

Mas não deixa de ser curioso que o Boletim de Urna não tenha o horário ajustado nestes casos em que a urna recebe os votos de outra urna.

**Comment by vjoao** [comment]
Por nada, somente com a auditoria dos dados que podemos manter a transparência! Parabéns pelo trabalho.

**Comment by danarrib** [comment]
Consertado no 05eaf2fd9e
